services: mongodb
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: nosetests
